### ISSUE TITLE
Lỗi khi Share link to feed

### ISSUE THREAD

**Issue by vinhtran6921** [maitrungduc1410/react-native-zalo-kit#10]
Lần đầu tiên khi call postToWallByApp -> mở sang app zalo (Cấp quyền truy cập) sau đó app tự tắt xuống ngay lập tức. Lần thứ 2 call thì mới vào đc trang đăng bài viết của zalo (Ko hiện màn hình cấp quyền truy cập nữa) .
Thanks bạn.
Video: https://vimeo.com/user129179317/review/490670268/96c0b09e33
Code: 
```
 try {
      const feedData = {
        appName: 'Utop', // appname back to app when cancel
        message: 'Hello World',
        link: 'https://zing.vn',
        linkTitle: 'TITLE DDAAY',
        linkSource: 'LIN SOURCE DAY',
        linkDesc: 'LINK DESC DAY',
        linkThumb: [
          'https://utopmspocst.blob.core.windows.net/asset-0543bc97-a526-4ab4-96f6-b0770ab3ba6c/Thumbnail_b75e6008171d4204a68ae1d8d723a6b1_000001.png',
        ],
        others: {},
      };
      const data = await postToWallByApp(feedData);
      // console.log(`%c data`, 'color: blue; font-weight: 600', data);

      /*
          returns: {
            success: true,
            data: "<raw message>",
            message: "format message",
            sendAction: 0 or 1 (0: sent, 1: cancelled)
          }
        */
    } catch (error) {
      console.log(error);
    }
```

**Comment by maitrungduc1410** [comment]
mình sẽ check lại và reply cho bạn sớm nhất nhé

**Comment by maitrungduc1410** [comment]
Mình check lại thì thấy vẫn oke nhé bạn. Bạn thử project demo này của mình nhé: https://github.com/maitrungduc1410/test-zalo-kit.

Cả khi chưa login hoặc đã login mà `postToWallByApp` thì đều oke 1 lần là được.

Mình đã test lại (trên iOS) với các trường hợp:
- 1. App Zalo đã login từ trước, bên phía React native bấm Login -> sang app cấp quyền truy cập -> quay trở lại app RN, bấm `postToWallByApp`
- 2. App Zalo vẫn login từ trước, bên phía RN logout -> bấm luôn `postToWallByApp` vẫn oke
- 3. App Zalo đã logout, bên phía RN logout ra, sau đó bấm luôn `postToWallByApp` thì vẫn chỉ 1 lần là oke luôn

**Comment by vinhtran6921** [comment]
Đây là video mình test project của bạn trên android. nó vẫn bị lỗi phải click 2 lần mới vào chỗ share trên zalo đc.
https://drive.google.com/file/d/1RW1APsbB-oDg_L6BN60V_2QH67alnt_9/view?usp=sharing

**Comment by maitrungduc1410** [comment]
oke bạn có thể có vấn đề bên Android, mình cần check lại. 

Vấn đề là giờ ko còn cái đt Android nào :cry :cry

**Comment by vinhtran6921** [comment]
Mình thì lại ko có con iphone nào để test trên ios =))

**Comment by maitrungduc1410** [comment]
hello mọi người, mình mới release bản mới (2.1.0) fix các lỗi liên quan, các bạn cài lại và test lại mình với nhé (nhớ chạy lại `pod install`)
