### ISSUE TITLE
Lỗi không getUserProfile

### ISSUE THREAD

**Issue by anhdo9797** [maitrungduc1410/react-native-zalo-kit#11]
![image](https://user-images.githubusercontent.com/60549336/102845889-289ef080-4441-11eb-8219-e2cb630132e5.png)
em login xong thì log cái profile nhưng không được
anh giúp em với

**Comment by anhdo9797** [comment]
![image](https://user-images.githubusercontent.com/60549336/102862248-601e9480-4463-11eb-93fa-9ba87b2d4c79.png)
code em check thế này như nó chỉ check được trạng thái thôi ạ 
![Uploading image.png…]()

**Comment by maitrungduc1410** [comment]
E chạy thử project demo này của a nhé: https://github.com/maitrungduc1410/test-zalo-kit

Ở đó vẫn get userprofile bình thường đó e

**Comment by maitrungduc1410** [comment]
hello mọi người, mình mới release bản mới (2.1.0) fix các lỗi liên quan, các bạn cài lại và test lại mình với nhé (nhớ chạy lại `pod install`)
