### ISSUE TITLE
Lỗi android - login zalo qua app zalo ko trả về authCode (khi chưa login sẵn tài khoản zalo trên app)

### ISSUE THREAD

**Issue by ThangPh96** [maitrungduc1410/react-native-zalo-kit#12]
Mình test app demo thì khi login zalo trên android qua app zalo, trường hợp app zalo chưa đăng nhập sẵn tài khoản zalo.
https://github.com/maitrungduc1410/test-zalo-kit

Khi gọi hàm ZaloKit.login, nhảy qua app zalo và login  vào account zalo, sau đó back lại về app demo thì không trả về authCode và cũng  ko trả về error trong callback hàm ZaloKit.login.

Trong khi đó getUserProfile và isAuthenticated thì vẫn ra kết quả.
Bạn cho mình hỏi nguyên nhân lỗi này, mình cảm ơn!

**Comment by maitrungduc1410** [comment]
chào bạn mình sẽ debug lỗi này và reply lại cho bạn sớm nhé

**Comment by ThangPh96** [comment]
Cảm ơn bạn đã reply.
Mình có tham khảo doc của zalo ở link https://developers.zalo.me/docs/sdk/android-sdk-8. Mình thấy rect-native-zalo-kit đang làm đúng theo hướng dẫn rồi. 
Mình xem trên zalo support thì khá nhiều bạn bị lỗi này, có 1 issue được trả lời https://developers.zalo.me/community/detail/af5dccbef0fb19a540ea
Theo đó mình kiểm tra listener đã khác null trước khi gọi authenticate, nhưng vẫn bị lỗi trên.
Mình có test thử demo do zalo cung cấp https://github.com/VNG-Zalo/ZaloSDK-Android-Demo thì không bị lỗi trên, nhưng demo viết bằng kotlin.
Theo mình nghĩ lỗi này là do zalo android sdk với java, nhưng tạm thời mình chưa có thời gian tìm hiểu tiếp. Mong là những thông tin sẽ ít nhiều hỗ trợ bạn. Rất mong được bạn hỗ trợ xử lý, mình cảm ơn nhiều!

**Comment by maitrungduc1410** [comment]
cám ơn bạn vì những chi tiết trên nhé :)

**Comment by maitrungduc1410** [comment]
hello mọi người, mình mới release bản mới (2.1.0) fix các lỗi liên quan, các bạn cài lại và test lại mình với nhé (nhớ chạy lại `pod install`)
