### ISSUE TITLE
Login endpoint v3

### ISSUE THREAD

**Issue by quannguyennn** [maitrungduc1410/react-native-zalo-kit#13]
Mình thấy trang chủ zalo dev thông báo migrate sang endpoint login v3 từ 1/4/2021 thì có ảnh hưởng gì đến lib không bạn?

**Comment by maitrungduc1410** [comment]
mình cần phải test lại và nếu cần thì migrate lên version mới, mình sẽ reply vào đây cho bạn sớm nhé

**Comment by maitrungduc1410** [comment]
Bạn có thể gửi link cho mình đc ko, mình tìm nhưng ko thấy thông bao migrate sang v3 như bạn nói

**Comment by quannguyennn** [comment]
https://developers.zalo.me/docs/api/developer-notification/dung-ho-tro-duong-dan-dang-nhap-zalo-v2-post-4827

**Comment by maitrungduc1410** [comment]
cái đó liên quan tới phần web api của họ, mình ko thấy họ nói gì tới bên mobile SDKs, ko chắc có thay đổi j ko :))
