### ISSUE TITLE
Lỗi login lần đầu

### ISSUE THREAD

**Issue by anhdo9797** [maitrungduc1410/react-native-zalo-kit#22]
![Screen Shot 2021-06-24 at 08 42 55](https://user-images.githubusercontent.com/60549336/123189540-2e48c200-d4c8-11eb-9c75-341dae76a941.png)

hi anh, đầy là code của em để login với zalo
vấn đề của em là lúc app Zalo chưa đăng nhập, lúc đó em call hàm trên thì nó chỉ login xong ko chạy tiếp những dòng dưới, log oathCode không có, nhưng nếu app Zalo đã đăng nhập thì nó vẫn chạy bình thường

Mong a cho giải pháp cho vấn đề này với ạ

**Comment by maitrungduc1410** [comment]
e đang bị vấn đề này trên Android hay iOS thế e?

**Comment by anhdo9797** [comment]
dạ trên android

**Comment by maitrungduc1410** [comment]
hello mọi người, mình mới release bản mới (2.1.0) fix các lỗi liên quan, các bạn cài lại và test lại mình với nhé (nhớ chạy lại `pod install`)
