### ISSUE TITLE
Lỗi getUserProfile

### ISSUE THREAD

**Issue by PiPyL** [maitrungduc1410/react-native-zalo-kit#23]
![image](https://user-images.githubusercontent.com/34052864/125727591-46525fac-84b9-4320-a33a-c226c3932267.png)

Error: Success
    at Object.promiseMethodWrapper [as getUserProfile] (NativeModules.js:103)
    at _callee2$ (Login.js:194)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:154)
    at runtime.js:164
    at tryCallOne (core.js:37)
    at core.js:123

Mình login thành công có authCode nhưng sau đó call getUserProfile thì nó lại bị lỗi như trên. Bạn nào biết cách fix chỉ mình với! Mình cám ơn.

**Comment by hiiamtrong** [comment]
Mình cũng đang gặp vấn đề tương tự, @PiPyL bạn fix được phần này chưa vậy

**Comment by hiiamtrong** [comment]
@maitrungduc1410 anh có thể giúp đỡ bọn em issue này không ạ

**Comment by maitrungduc1410** [comment]
@hiiamtrong lí do hơi củ chuối nhưng lâu rồi mình ko update gì vào repo này là do mình ko có Android device để test :))

oke thấy có mấy bạn bị lỗi này và các lỗi khác, tuần tới mình sẽ tìm 1 con Android và fix tất cả các lỗi các bạn đã report nhé

**Comment by hiiamtrong** [comment]
@maitrungduc1410 em cảm ơn anh ạ

**Comment by maitrungduc1410** [comment]
hello mọi người, mình mới release bản mới (2.1.0) fix các lỗi liên quan, các bạn cài lại và test lại mình với nhé (nhớ chạy lại `pod install`)
