### ISSUE TITLE
lỗi ko run trên android

### ISSUE THREAD

**Issue by tuankhanh45** [maitrungduc1410/react-native-zalo-kit#30]
sau khi config android build : 
Could not find any matches for com.zing.zalo.zalosdk:openapi:+ as no versions of com.zing.zalo.zalosdk:openapi are available.
"dependencies": {
    "@react-native-google-signin/google-signin": "^7.0.0-alpha.3",
    "react": "17.0.2",
    "react-native": "0.65.1",
    "react-native-webview": "^11.13.0",
    "react-native-zalo-kit": "^1.0.9"
  },

**Comment by dichakho** [comment]
Mình đã thử như sau và nó hoạt động đối với mình
1. Mở **android/build.gradle**
          ```
allprojects {
              repositories {
                  ...
                  jcenter()
                  ...
              }
}
```
2. Mở **android/app/build.gradle**
        ```
 dependencies {
            ...
            implementation "com.zing.zalo.zalosdk:core:2.4.1030"
            implementation "com.zing.zalo.zalosdk:auth:2.4.1030"
            implementation "com.zing.zalo.zalosdk:openapi:2.4.1030"
            ....
}
```
3. Mở **proguard-rules.pro**
```
-keep class com.zing.zalo.**{ *; }
-keep enum com.zing.zalo.**{ *; }
-keep interface com.zing.zalo.**{ *; }
```

**Comment by maitrungduc1410** [comment]
hello mọi người, mình mới release bản mới (2.1.0) fix các lỗi liên quan, các bạn cài lại và test lại mình với nhé (nhớ chạy lại `pod install`)
