### ISSUE TITLE
Not working on android 11 or higher

### ISSUE THREAD

**Issue by suupham2506** [maitrungduc1410/react-native-zalo-kit#34]
It crashes right away and throw this error. 
Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://oauth.zaloapp.com/... cmp=com.vnpay.abbank/.activity.WebActivity } from ProcessRecord{63c4246 2563:vn.kilo.kiloretailer/u0a933} (pid=2563, uid=10933) not exported from uid 10844

**Comment by maitrungduc1410** [comment]
can you let me know which android version you're using?

**Comment by suupham2506** [comment]
> hich android version you're using?

I am using android 11, it crashes right when I login with zalo.

**Comment by longquangpham90** [comment]
Plesae help me update readme.md version 4.0.1

**Comment by maitrungduc1410** [comment]
@longquangpham90  no change from your developer perspective, so no change in README, needed

**Comment by longquangpham90** [comment]
@maitrungduc1410 so i think, i have the same issue, but about for issue every mobile Android
I can not get oauthCode
I think because Zalo update v4 and library not change module success

**Comment by maitrungduc1410** [comment]
from your side you don't ever need to use the `oauthCode`, in v4 we'll use access token, let me update my README a bit to clear this point

**Comment by maitrungduc1410** [comment]
@longquangpham90 just updated my README, in Login method: https://github.com/maitrungduc1410/react-native-zalo-kit#login

But you probably never need to handle accessToken and refreshToken your self, it's already managed by the library
