### ISSUE TITLE
[android] build Error with version 2.1.1

### ISSUE THREAD

**Issue by maugou** [maitrungduc1410/react-native-zalo-kit#35]
### Description 
Error "Could not find symbol class.." when building with version 2.1.1 on Android. Version 1.0.9 works fine.
<img width="483" alt="스크린샷 2021-12-21 오전 10 32 22" src="https://user-images.githubusercontent.com/22266526/146855634-d62b9acb-16f7-4c09-aaee-9ab88ed74fb6.png">

### Version
"react": "16.13.1"
"react-native": "0.63.3"
"react-native-zalo-kit": "2.1.1"

**Comment by maitrungduc1410** [comment]
thanks for reporting bug, I'm going to look into this

**Comment by mrtaiw** [comment]
vô build.gradle thêm vào dependencies:
implementation "me.zalo:sdk-core:+"
implementation "me.zalo:sdk-auth:+"
implementation "me.zalo:sdk-openapi:+"

**Comment by maitrungduc1410** [comment]
thanks @mrtaiw

**Comment by maitrungduc1410** [comment]
Hi all, please install `2.1.3` I fixed this issue, no need to manually `implementation "me.zalo:sdk-core:xxx` yourself, now it should be installed automatically
