### ISSUE TITLE
[android] web login Error

### ISSUE THREAD

**Issue by maugou** [maitrungduc1410/react-native-zalo-kit#36]
### Description

When I log in via web on Android, I get the following error. (If the Zalo app is not installed on the device). Tested on Android versions 9 and 11.

On iOS it works fine

![Screenshot](https://user-images.githubusercontent.com/22266526/147026026-bc0b9b7f-26fe-4e25-8b47-afa84acbf0d8.jpg)

### Version
"react": "16.13.1"
"react-native": "0.63.3"
"react-native-zalo-kit": "2.1.3" or "1.0.9"

**Comment by maitrungduc1410** [comment]
are you using Emulator, can you upgrade to version `2.1.3` and try on real Android device?

**Comment by maugou** [comment]
> 

The text content has been corrected. sorry.
The above symptoms are the symptoms tested on the actual Android 2.1.3 version.

**Comment by maugou** [comment]
> are you using Emulator, can you upgrade to version `2.1.3` and try on real Android device?

The text content has been corrected. sorry.
The above error was actually tested on Android 2.1.3 version.

**Comment by maugou** [comment]
> are you using Emulator, can you upgrade to version `2.1.3` and try on real Android device?

The text content has been corrected. sorry.
The above error was tested with version 2.1.3 on a real Android device.

**Comment by longhuynhthanh** [comment]
> are you using Emulator, can you upgrade to version `2.1.3` and try on real Android device?
same íssue

**Comment by hgbao** [comment]
same issuse here

**Comment by deanzhang380** [comment]
Same issue.
With Android SDK 29 works fine.
But change to Android SDK 30 will have above issue

**Comment by maitrungduc1410** [comment]
hi all, please upgrade to latest version

**Comment by longhuynhthanh** [comment]
> hi all, please upgrade to latest version

I upgrade version 4.0.3 still suffer

**Comment by maugou** [comment]
> hi all, please upgrade to latest version

thank you
