### ISSUE TITLE
getUserProfile is not working!!! ([Error: [Warning] AccessToken should be placed in header])

### ISSUE THREAD

**Issue by NguyenVanHoang19** [maitrungduc1410/react-native-zalo-kit#37]
Tôi đã sử dụng thư viện react-native-zalo-kit version 2.1.3 và đã gặp lỗi khi sử dụng hàm getUserProfile() trên android 11 (redmi note 8 pro và cả ở máy ảo android).

Khi gọi hàm getUserProfile() tôi đã gặp lỗi là:  **[Error: [Warning] AccessToken should be placed in header].**

- Tôi đã test ở project test-zalo-kit từ demo của bạn vẫn gặp lỗi tương tự. 
![error](https://user-images.githubusercontent.com/64886731/150085448-b258f10b-a3d1-4792-9100-d25d71cd1826.png)

Mong được mọi người hỗ trợ ạ.!
Cảm ơn!!!

**Comment by maitrungduc1410** [comment]
oke các bạn mình sẽ check lại nhé

**Comment by maitrungduc1410** [comment]
@NguyenVanHoang19  @vinhtruong93  các bạn upgrade lên bản `4.0.1` nhé
