### ISSUE TITLE
Lỗi không đăng nhập được

### ISSUE THREAD

**Issue by hungpd-1505** [maitrungduc1410/react-native-zalo-kit#4]
Chào bạn,

Mình đang thử sử dụng thư viện này vào ứng dụng reactnative, tạo ra 1 button login để đăng nhập qua zaloapp.
nhưng khi click vào thì lại hiển thị ra màn hình và lỗi như sau. 

Mình đã xem hướng dẫn, cài đặt appid đầy đủ rồi.
Nhờ bạn hỗ trợ giúp mình nhé. thanks nhiều!

![Simulator Screen Shot - iPhone 11 - 2020-07-29 at 13 28 50](https://user-images.githubusercontent.com/43594321/88764629-79b2fd00-d19f-11ea-8569-d290f711bef8.png)

**Comment by maitrungduc1410** [comment]
mình sẽ test lại và reply cho bạn sớm nhé

**Comment by hungpd-1505** [comment]
cảm ơn ban nhiều. (F)

**Comment by maitrungduc1410** [comment]
chào bạn, 

mình đã test lại, code vẫn chạy bình thường nhé, và sau khi debug thì mình phát hiện ra lỗi của bạn là do bạn test trên iOS mà chưa đăng kí BundleID trên trang Zalo developer

<img width="1438" alt="Screenshot 2020-07-30 at 09 42 14" src="https://user-images.githubusercontent.com/16630193/88870929-3a40eb00-d249-11ea-945d-126fc264647c.png">

Mình đã thử (xoá bundleID) thì nhận lỗi tương tự.

**Comment by hungpd-1505** [comment]
ok
cảm ơn bạn rất nhiều. khả năng là do lỗi này rồi, xin phép close nhé
chúc bạn 1 ngày mới tốt lành
