### ISSUE TITLE
Login zalo in android not work

### ISSUE THREAD

**Issue by longhuynhthanh** [maitrungduc1410/react-native-zalo-kit#45]
Login zalo in iOS work, but android is errored like picture

**Comment by maitrungduc1410** [comment]
Please check: your android project package name, app hash key and make sure the value you register in Zalo developer portal is correct

**Comment by longhuynhthanh** [comment]
> Please check: your android project package name, app hash key and make sure the value you register in Zalo developer portal is correct

thanks br
