### ISSUE TITLE
Don't open app Zalo

### ISSUE THREAD

**Issue by longhuynhthanh** [maitrungduc1410/react-native-zalo-kit#48]
When login zalo version 4.0.3 only open web, don't open app althought I installed, please helping bro

**Comment by maitrungduc1410** [comment]
which platform are u testing? android or ios?

**Comment by longhuynhthanh** [comment]
iOS and android

**Comment by maitrungduc1410** [comment]
have u done ios setup? https://github.com/maitrungduc1410/react-native-zalo-kit#ios

**Comment by longhuynhthanh** [comment]
yes, I have the same setup

**Comment by longhuynhthanh** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2022-05-09 at 12 04 05](https://user-images.githubusercontent.com/38778007/167343958-60851990-9f62-4513-83e9-8c40dc4f2413.png)
I login account zalo, but don't connect this account. Android connect this account but open web, not open app

**Comment by maitrungduc1410** [comment]
For android, in `Manifest.xml`, make sure you have:

```xml
...
    <queries>
      <package android:name="com.zing.zalo" />
    </queries>
</manifest>
```

For iOS, make sure you add `LSApplicationQueriesSchemes`

Check README again, I updated ios + android setup
