### ISSUE TITLE
[IOS] Error Thread 1: signal SIGABRT after post to feed via Zalo App and back to app

### ISSUE THREAD

**Issue by DaoThDanh1997** [maitrungduc1410/react-native-zalo-kit#5]
Chào bạn,

Trước hết, mình xin cảm ơn bạn vì package này.

Hiện tại mình đang có 1 issue là mình có dùng chức năng postToWallByApp(), nhưng sau khi post thành công và mình bấm Quay trở về app thì mình bị lỗi như hình dưới đây
![Screen Shot 2020-07-30 at 23 08 07](https://user-images.githubusercontent.com/61119317/88946693-bf63e880-d2b9-11ea-86e0-eccf7820ecd8.png)

Setting của mình đang để ở URL Types hiện tại như hình dưới
![Screen Shot 2020-07-30 at 23 11 55](https://user-images.githubusercontent.com/61119317/88947091-3e592100-d2ba-11ea-8279-1eb810cc6e5d.png)

Nhờ bạn hỗ trợ giúp mình chỗ này. Mình xin cảm ơn nhiều.

**Comment by maitrungduc1410** [comment]
Project này bạn đang dùng phiên bản RN bao nhiêu đó? Phần setup with URL Types thì mình ko rõ ý bạn là gì, bạn follow theo docs của mình setup ở file `AppDelegate.m` nhé. 

Mình sẽ test lại chức năng này và feedback cho bạn sớm

**Comment by DaoThDanh1997** [comment]
Mình xài RN 0.63.2
Phần URL types mình set dựa theo doc của Zalo phần "Thêm URL Type"
https://developers.zalo.me/docs/sdk/ios-sdk-9

**Comment by maitrungduc1410** [comment]
Chào bạn,

Mình đã fix lỗi này, bạn update `react-native-zalo-kit` trong `package.json` lên bản `1.0.8` chạy lại `npm install` và cả `pod install` nhé

**Comment by DaoThDanh1997** [comment]
Chào bạn,

Mình đã test lại trên version mới và confirm issue này đã được fixed.

Cảm ơn bạn rất nhiều :)
