### ISSUE TITLE
Don't use to method sendMessageByApp or postFeedByApp

### ISSUE THREAD

**Issue by longhuynhthanh** [maitrungduc1410/react-native-zalo-kit#52]
I used to method sendMessageByApp, but don't open zalo app, open Zalo on Store(ch play or Appstore)

**Comment by maitrungduc1410** [comment]
For android, in `Manifest.xml`, make sure you have:

```xml
...
    <queries>
      <package android:name="com.zing.zalo" />
    </queries>
</manifest>
```

For iOS, make sure you add `LSApplicationQueriesSchemes`

Check README again, I updated ios + android setup
