### ISSUE TITLE
Lỗi bạn chưa cài Zalo

### ISSUE THREAD

**Issue by chuhoanglong** [maitrungduc1410/react-native-zalo-kit#54]
Tôi đang phát triển tính năng đăng nhập với Zalo trên React native nhưng trên một số máy android tôi nhận được lỗi như hình sau:
(máy android 11)
![image](https://user-images.githubusercontent.com/37845536/182342387-c1d42331-9c2c-49a9-a882-4bf7838ea415.png)

một số máy android vẫn đăng nhập được bình thường.
Cảm ơn bạn vì đã hỗ trợ!

**Comment by taleduykhang** [comment]
@chuhoanglong chu
bạn cần thêm đoạn code dưới đây vào AndroidManifest.xml đối với android 11 trở lên
`<queries>
        <package android:name="com.zing.zalo" />
</queries>`

**Comment by maitrungduc1410** [comment]
bạn thêm code sau vào file manifest.xml là được nhé:

```xml
...
    <queries>
      <package android:name="com.zing.zalo" />
    </queries>
</manifest>
```
