### ISSUE TITLE
Lỗi chưa cài zalo/ có lỗi trong quá trình truy cập

### ISSUE THREAD

**Issue by canhvinh99** [maitrungduc1410/react-native-zalo-kit#56]
Tôi đang phát triển tính năng đăng nhập với Zalo trên React native. Trên android 12 tôi nhận được lỗi chưa cài zalo (dù đã cài) và trên androd 9 tôi nhận được "có lỗi trong quá trình truy cập". Log trên android9:
![image](https://user-images.githubusercontent.com/84773529/191414547-8ae01d43-4f97-463f-b88d-6f6e3726b027.png)

**Comment by maitrungduc1410** [comment]
bạn thêm code sau vào file manifest.xml là được nhé:

```xml
...
    <queries>
      <package android:name="com.zing.zalo" />
    </queries>
</manifest>
```
