### ISSUE TITLE
Share Photo by sendMessageByZalo 

### ISSUE THREAD

**Issue by vanhoang2012** [maitrungduc1410/react-native-zalo-kit#60]
How to add attachment with function sendMessageByZalo

**Comment by hungcuongDev** [comment]
Bạn cài thư viện này có build đc release không, mình cứ bị lỗi linked command failed

**Comment by maitrungduc1410** [comment]
mình sẽ check lại và nhắn các bạn nhé

**Comment by maitrungduc1410** [comment]
in `sendMessage`  function you can pass in the URL of your attachment with `link`.

Zalo SDK doesn't support sending attachment directly as file

```
import { sendMessage } from 'react-native-zalo-kit'

const sendMessage = async () => {
  try {
    const friendId = 'friend_ID'
    const link = 'https://zing.vn'
    const message = 'Hello World'
    const data = await sendMessage(friendId, message, link)
    console.log(data)

    /*
      returns: {
        to: 'friend_ID'
      }
    */
  } catch (error) {
    console.log(error)
  }
}
```

**Comment by KevinA-cpu** [comment]
Hi, I tried using SendMessage and it would always return "Application is not registered for this request." I have made sure that I request every api permission for my app in Zalo Developer

**Comment by maitrungduc1410** [comment]
> Bạn cài thư viện này có build đc release không, mình cứ bị lỗi linked command failed

Mình build bình thường bạn ạ, bạn check lại xem nhé.
- RN: 0.72.3
- command: `npx react-native build-android --mode=release`
