### ISSUE TITLE
Không phản hồi response khi login lần đầu trên trình duyệt.

### ISSUE THREAD

**Issue by KienHung027** [maitrungduc1410/react-native-zalo-kit#7]
Hiện tại e login lần đầu trên trình duyệt thì không nhận được phản hồi, cũng như lỗi gì. Mọi ngừoi ai gặp qua, cho e xin hướng khắc phục.

**Comment by maitrungduc1410** [comment]
e đang gặp phải lỗi này trên iOS hay Android hay cả 2 vậy e?

**Comment by KienHung027** [comment]
lỗi này e mắc phải bên android anh!

**Comment by maitrungduc1410** [comment]
Chào e,

a đã test lại, mọi thứ vẫn oke nhé. Login bằng option `AUTH_VIA_WEB` vẫn hoạt động bình thường (cả 2 option còn lại cũng vậy).

E đọc kĩ lại hướng dẫn setup của a:
- Check kĩ xem Zalo App ID đã đúng hay chưa
- Android App Hash Key đã đúng hay chưa
- Ở `AndroidManifest.xml` đã có `BrowserLoginActivity` hay chưa
