### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by tuandt-dev** [maitrungduc1410/react-native-zalo-kit#75]
{"error_name":"Invalid android package","error_reason":"package name is invalid","ref_doc":"https://developers.zalo.me/docs/api/social-api/tham-khao/user-access-token-post-4316","error_description":"Invalid android package","error":-14009}.

**Comment by maitrungduc1410** [comment]
Can you check Troubleshooting section in Readme to see if it helps?

**Comment by tuandt-dev** [comment]
not helping still get the error

**Comment by maitrungduc1410** [comment]
As the error is showing, probably your package name is different from the one in Zalo developer portal

**Comment by tuandt-dev** [comment]
getApplicationHashkey return {"_h": 0, "_i": 0, "_j": null, "_k": null}

**Comment by maitrungduc1410** [comment]
are you using Emulator or real device, this should be in real device
