### ISSUE TITLE
Login zalo ở android app thời gian chờ quá lâu

### ISSUE THREAD

**Issue by VietKyle** [maitrungduc1410/react-native-zalo-kit#76]
Mình đang sử dụng plugin react-native-zalo-kit để đăng nhập bằng zalo cho ứng dụng. Cách đây khoảng 6 tháng thì hoạt động bình thường nhưng vài tháng trở lại đây login zalo rất lâu, thường xuyên chờ không dưới 5 phút.
Mình đang dùng react-native 0.71, React 18.2 và React-native-zalo-kit 4.0.3

**Comment by maitrungduc1410** [comment]
oke mình sẽ test lại nhé, 

bạn bị trên ios hay android?

**Comment by VietKyle** [comment]
Mình đang build react-native cho android thôi ạ

**Comment by maitrungduc1410** [comment]
> Mình đang build react-native cho android thôi ạ

oke bạn để mình check lại

**Comment by maitrungduc1410** [comment]
Mình reproduce được lỗi của bạn rồi.

Đầu tiên mình có 1 project A, setup các thứ, chạy lên login ngon lành.

Tiếp theo mình generate 1 project B, setup các thứ nhưng dùng chung Zalo App ID với app A, dẫn tới việc ở bước setup URL Types thì ta có giá trị giống như app A.

Nên khi chạy app B -> Bấm Login -> Mở App Zalo -> Gọi về app A, trong khi nếu đúng ra nó phải gọi về app B

-->> trường hợp này là ta bị trùng giá trị URL types nên nó Deep Linking ko đúng cái ta muốn, và cái `await Login` sẽ ko bao giờ trả về

Nếu bạn đang bị như vậy thì:
- xoá các app khác đi chỉ giữ lại 1 cái
- hoặc dùng 1 cái Zalo App ID khác

**Comment by thanhvu260696** [comment]
ù em lại để cái đó cuối cùng
nếu để lên đầu thì có ảnh hưởng gì đến các thằng như line vs FB k a nhỉ

**Comment by thanhvu260696** [comment]
<img width="617" alt="Screenshot 2024-01-25 at 14 07 29" src="https://github.com/maitrungduc1410/react-native-zalo-kit/assets/72533291/dc2e2a55-00a1-4314-9b9d-40bcb339ef60">
nếu emem thêm cả line cả zalo nó đang báo Duplicate declaration of method 'application:openURL:options:' a chỉ em cách sửa nó với được không ạ em ngu native quá

**Comment by maitrungduc1410** [comment]
> <img width="617" alt="Screenshot 2024-01-25 at 14 07 29" src="https://github.com/maitrungduc1410/react-native-zalo-kit/assets/72533291/dc2e2a55-00a1-4314-9b9d-40bcb339ef60">
> 
> nếu emem thêm cả line cả zalo nó đang báo Duplicate declaration of method 'application:openURL:options:' a chỉ em cách sửa nó với được không ạ em ngu native quá

E gộp chung 2 thằng lại dùng dấu "||" như ví dụ của a ấy nhé.

**Comment by thanhvu260696** [comment]
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<NSString *, id> *)options {
     if ([[url scheme] isEqualToString:@"line"]) {
        // Handle redirection back to the app from Line
        return [LineLogin application:application open:url options:options];
    } else {
        return [[ZDKApplicationDelegate sharedInstance] application:application openURL:url options:options];
    }
}
chat GPT nó gợi ý cho em :D

**Comment by thanhvu260696** [comment]
- (BOOL)application:(UIApplication *)application openURL:(nonnull NSURL *)url options:(nonnull NSDictionary<NSString *,id> *)options {
  return [[ZDKApplicationDelegate sharedInstance] application:application openURL:url options:options]||[LineLogin application:application open:url options:options];
} ý của a có phải như này không ạ

**Comment by maitrungduc1410** [comment]
Đừng if else e, làm như ví dụ của a ấy, dùng dấu `||`

**Comment by thanhvu260696** [comment]
em cảm ơn a nhiều nhé =)) bồi tu thêm native thôi chứ ngu quá =.=!

**Comment by maitrungduc1410** [comment]
> em cảm ơn a nhiều nhé =)) bồi tu thêm native thôi chứ ngu quá =.=!

Ai cũng giỏi native hết thì lib như của a vứt đi hết e ạ 😂

**Comment by maitrungduc1410** [comment]
@VietKyle bạn check lại trên máy khác giúp mình nhé, check cả network của bạn nữa nhé

**Comment by VietKyle** [comment]
> @VietKyle bạn check lại trên máy khác giúp mình nhé, check cả network của bạn nữa nhé

Mình đã thử trên dòng máy xiaomi, samsung ạ, và mình cũng thử chuyển qua 4G, nhưng vẫn như vậy ạ
