### ISSUE TITLE
 getApplicationHashKey() not working in release

### ISSUE THREAD

**Issue by thanhvu260696** [maitrungduc1410/react-native-zalo-kit#79]
chào bạn ở android mình có sử dụng getApplicationHashKey() cho zalo dev key hash nhưng vấn đề mình đang gặp phải là build dev thì key đó hoạt động bt còn nếu build ra bản release thì key đó báo key hash không hợp lệ bạn có thể xem và cho mình hướng giải quyết được không

**Comment by maitrungduc1410** [comment]
bạn screenshot mình xem lỗi với nhé

**Comment by thanhvu260696** [comment]
![z5103074156015_c3b0399e0cbc5ebaaf528bc69912df5d](https://github.com/maitrungduc1410/react-native-zalo-kit/assets/72533291/a14ee1bd-6afe-439e-bef9-07b2145771f2)
nó báo lỗi này bạn ạ với cả mình để ý là dùng getApplicationHashKey() của sdk thì nó gen ra không khác cái key mà trong demo ở lib của bạn mong bạn sp mình chỗ này với

**Comment by maitrungduc1410** [comment]
> với cả mình để ý là dùng getApplicationHashKey() của sdk thì nó gen ra không khác cái key mà trong demo ở lib

ý bạn là sao nhỉ?

**Comment by maitrungduc1410** [comment]
Sau khi bạn build release thì bạn có gen lại hashKey mới và update trên Zalo developer portal ko?

**Comment by maitrungduc1410** [comment]
mình có test trên Emulator, build release:
```
yarn android --mode release
```

Vẫn oke bạn ạ

<img width="1763" alt="Screenshot 2024-01-25 at 10 04 47 AM" src="https://github.com/maitrungduc1410/react-native-zalo-kit/assets/16630193/837fffdb-7a63-41ca-9d6c-b130ff037ca2">

**Comment by thanhvu260696** [comment]
em cũng build mode release nhưng click vào log getApplicationHashKey() thì bị crash

**Comment by thanhvu260696** [comment]
npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 13.6.1
  CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Memory: 41.87 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: ~/Desktop/project/VGS/mobile-app-ngan-tuan-phat/node_modules/.bin/yarn
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by thanhvu260696** [comment]
> Sau khi bạn build release thì bạn có gen lại hashKey mới và update trên Zalo developer portal ko?

ngoài cái docs anh đưa ra em cũng chưa biết gen key release kiểu gì :)) a chỉ e với được k với cả nếu e build ở info bên trên thì nó sẽ bị lỗi vậy 
<img width="856" alt="Screenshot 2024-01-25 at 10 54 26" src="https://github.com/maitrungduc1410/react-native-zalo-kit/assets/72533291/908c194e-8a30-4203-b1e6-b0e4869eb06d">
nên e vào lib thử đẩy dòng này lên 30 không biết có ảnh hưởng gì không nhỉ
<img width="721" alt="Screenshot 2024-01-25 at 13 07 18" src="https://github.com/maitrungduc1410/react-native-zalo-kit/assets/72533291/20aca571-ccd0-42c6-b522-a67cd082b61c">
nhưng em đẩy lên thì nó build được

**Comment by thanhvu260696** [comment]
@@! tưởng nó là key nào hoá ra giống key em gen base 64 của FB em thêm thì nó chạy trên simulator release r a ạ

**Comment by thanhvu260696** [comment]
em cảm ơn a nhiều nhé có gì không hiểu hay làm sao em xin phép liên hệ a sau ạ
