### ISSUE TITLE
Lỗi không phản hồi ở lần Login đầu tiên trên ứng dụng Zalo (nếu trước đó ứng dụng Zalo chưa được login)

### ISSUE THREAD

**Issue by quangkhaidam93** [maitrungduc1410/react-native-zalo-kit#8]
Chào anh,

Em đang gặp vấn đề với việc đăng nhập ứng dụng Zalo nếu trước đó ứng dụng chưa đăng nhập (gọi hàm login() sẽ dẫn đến màn hình đăng nhập trên Zalo). Sau khi hoàn tất khâu đăng nhập trên ứng dụng Zalo thì nó sẽ back về ứng dụng chính nhưng không có gì xảy ra, phải thực hiện hành động ấn nút đăng nhập Zalo lần 2 mới có thể đăng nhập được.

Dependencies project em đang thực hiện:
+  "react-native": "0.60.5"
+ "react-native-zalo-kit": "^1.0.8"

**Comment by maitrungduc1410** [comment]
Khi Login e đang truyền vào tham số nào: `AUTH_VIA_APP_OR_WEB` ,...?

**Comment by quangkhaidam93** [comment]
dạ Constants.AUTH_VIA_APP_OR_WEB, e mới test lại là nếu dùng bằng web mà lần đầu đăng nhập cũng bị ạ. Em test trên Android thì sau khi gọi hàm login để nhảy sang web (Chrome) và hoàn thành khâu đăng nhập xong, nhảy ngược về ứng dụng chính và không gọi gì thêm, phải thực hiện ấn nút đăng nhập lần nữa mới vào đc. Cám ơn anh.

**Comment by maitrungduc1410** [comment]
oke e, 

có đoạn này a chưa clear lắm, `nhảy ngược về ứng dụng và ko có gì xảy ra`, ý e là mong muốn là nó phải được chuyển vào màn hình bên trong chứ ko phải ở màn login nữa đúng ko?

**Comment by quangkhaidam93** [comment]
dạ  đúng rồi anh, e có debug gắn log ở sau đoạn const oauthCode = await login(Constants.AUTH_VIA_APP_OR_WEB); thì e không thấy chạy log này ạ. Em nghĩ là vẫn chưa thực hiện resolve Promise ở hàm login.

**Comment by maitrungduc1410** [comment]
oke e a sẽ check và reply lại e sớm nhé

**Comment by quangkhaidam93** [comment]
Dạ em cảm ơn a trc :D

**Comment by maitrungduc1410** [comment]
Chào e,

A đã test lại mọi thứ chạy vẫn ngon mà e :)).

Demo e xem ở đây: https://github.com/maitrungduc1410/test-zalo-kit

A đã test thử trên cả iOS và Android, mỗi cái a đã test trên cả simulator/emulator và device thật, test cả 2 trường hợp login qua web và qua app đều ok, Login resolve và trả về authcode bình thường nhé e,

E nhớ đảm bảo là follow theo các bước setup a viết trong README nhé

**Comment by quangkhaidam93** [comment]
Dạ ok tks a. Anh có thử trường hợp mà down ứng dụng Zalo về và chưa đăng nhập. Xong từ app mình bật app Zalo và thực hiện đăng nhập, rồi tự động back về app mình chưa anh? Em thì đang bị stuck ở case này, còn mấy cái khác thì ok r anh. Cảm ơn anh rất nhiều.

**Comment by maitrungduc1410** [comment]
có luôn e, a thử logout app zalo ra trước, sau đó login vào nó sẽ back về và trả về authcode bình thường.

E test thử với project demo kia của a coi sao nhé, nếu vẫn có lỗi thì e test bằng device khác xem nhé e

**Comment by quangkhaidam93** [comment]
dạ ok a, để e test lại ạ. Cảm ơn anh nhiều :D

**Comment by wanderlust252** [comment]
@maitrungduc1410 anh ơi em clone demo của anh về và thay app id vào chạy trên device Android thật không được. Login xong trả về AUTH CODE nhưng ấn isAuthenticated thì false ạ.

**Comment by maitrungduc1410** [comment]
@wanderlust252 a sẽ check lại và reply cho e sớm nhé
