### ISSUE TITLE
ERRPR Login Zalo on React native IOS app 

### ISSUE THREAD

**Issue by NgocLe1001** [maitrungduc1410/react-native-zalo-kit#83]
I followed the instructions but got error when login via Zalo. The error is not detail. Hope you can help. Thanks all
Package:
"react-native": "0.73.6"
"react-native-zalo-kit": "^4.0.5",

<img width="362" alt="image" src="https://github.com/maitrungduc1410/react-native-zalo-kit/assets/57764602/39a79a96-b5e6-43ba-be0a-8bd2bd75608d">

**Comment by maitrungduc1410** [comment]
As the error is showing

Your bundleID which is registered on Zalo Dev Portal is incorrect

Pls double check,open Xcode and look for your bundleId (you can also view it in Info.plist)

**Comment by NgocLe1001** [comment]
The bundleId is matched with the one I declare on Zalo developer.
I wonder if we have to fill those input fields?
<img width="702" alt="image" src="https://github.com/maitrungduc1410/react-native-zalo-kit/assets/57764602/03471933-e8f8-4730-b852-6dfb0b12719b">

**Comment by NgocLe1001** [comment]
I hide it for security. But ít’s string like `com.abc.xyz`

**Comment by maitrungduc1410** [comment]
hmmm, as the error says, your bundle is invalid. Maybe you should check one more time, I have no idea since this error thrown by ZaloSDK itself

<img width="500" alt="Screenshot 2024-04-11 at 12 03 30 AM" src="https://github.com/maitrungduc1410/react-native-zalo-kit/assets/16630193/0b034495-e6b1-4ca9-861d-87e044804b86">

**Comment by NgocLe1001** [comment]
> hmmm, as the error says, your bundle is invalid. Maybe you should check one more time, I have no idea since this error thrown by ZaloSDK itself
> 
> <img alt="Screenshot 2024-04-11 at 12 03 30 AM" width="500" src="https://private-user-images.githubusercontent.com/16630193/321310932-0b034495-e6b1-4ca9-861d-87e044804b86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDA5MTEsIm5iZiI6MTcxMjg0MDYxMSwicGF0aCI6Ii8xNjYzMDE5My8zMjEzMTA5MzItMGIwMzQ0OTUtZTZiMS00Y2E5LTg2MWQtODdlMDQ0ODA0Yjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEzMDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ODAyYzhlODE5OTRkOWE5ZDlmMzliOGQ1YTc2ZTAwMmUwNzFlYjY0ZmZjNjJjNTVjY2YzOGM2YmQxMDkzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WbXiasiUfbUAwo_AgsGxH6ue7jBeJ0wP9bYkefPztCg">

Hi, cảm ơn bạn vì đã support giúp mình
Mình change bundleId thì đăng nhập thành công.
Tuy nhiên mình không hiểu vấn đề gì với cái bundleId cũ, có blacklist hay quy định về cái này không?
Cảm ơn bạn nhiều.
===
Hi, Thanks for your supporting.
This issue is solved when I change to another bundle id
However, I still don't no what problems with the old bundle id, I wonder if there are any rules or blacklist bundle ids
Btw, Thank you so much.

**Comment by maitrungduc1410** [comment]
You're welcome :)
