### ISSUE TITLE
Không mở app Zalo dù đã cài đặt rồi

### ISSUE THREAD

**Issue by hoangphucnst** [maitrungduc1410/react-native-zalo-kit#94]
Mình làm theo hướng dẫn và login bằng web vẫn bình thường nhưng login bằng app thì cứ hiện câu thông báo ứng dụng zalo chưa được cài đặt

**Comment by maitrungduc1410** [comment]
Api zalo ngừng support lâu phết rồi b ạ, lỗi liên miên, docs thì ko rõ ràng, bạn cân nhắc có tiếp tục dùng ko nhé, nhiều b comment mình cũng thấy nhưng hết cách rồi :))

**Comment by hoangphucnst** [comment]
Tại mình thấy ứng dụng Báo Mới còn login bằng Zalo được á nó đá qua app zalo được á :D

**Comment by hoangphucnst** [comment]
À mình mở được app zalo rồi nha nó thiếu chỗ quan trọng này
Để gọi qua Zalo App để cấp quyền truy cập, và khi share message hoặc feed, thì cần thêm các LSApplicationQueriesSchemes : Main target setting -> Info -> Custom iOS Target Properties  -> click + để add thêm LSApplicationQueriesSchemes

zalosdk: dùng để gọi qua Zalo App khi cần cấp quyền truy cập.
zaloshareext: dùng để gọi qua Zalo App khi cần share message hoặc feed.

**Comment by maitrungduc1410** [comment]
Ủa nếu là mấy cái đó mình có ghi rõ trong README mà? Bạn xem chưa?

**Comment by hoangphucnst** [comment]
> Ủa nếu là mấy cái đó mình có ghi rõ trong README mà? Bạn xem chưa?

mình có xem mình cấu hình rồi cái không biết sao nó sync lại cái mất tiêu lát mình check lại thì thấy mất nên thêm vô lại thì đc. thanks bạn
