### ISSUE TITLE
chia sẻ link bằng sendMessageByApp

### ISSUE THREAD

**Issue by kienndhn** [maitrungduc1410/react-native-zalo-kit#95]
Em đang dùng hàm sendMessageByApp để gửi link qua Zalo. Có cách nào để bỏ qua modal "Chia sẻ thành công" không bro?
![photo_6302878766627669008_y](https://github.com/user-attachments/assets/07f4103f-39eb-4ee1-af49-39ce6abd4a04)

Em cảm ơn ạ.

**Comment by maitrungduc1410** [comment]
SDK của Zalo rất limited và ko có option đó b ạ

**Comment by kienndhn** [comment]
> SDK của Zalo rất limited và ko có option đó b ạ

em cảm ơn ạ.
